{
  "hash": "d715e3356f939553808be2ecd662615e",
  "result": {
    "engine": "knitr",
    "markdown": "---\nfilters:\n - naquiz\nformat:\n  html:\n    toc: true\n    toc-location: left\n    toc-title: \"In this session:\"\n---\n\n# Workshop 1: Introduction to R {#sec-workshop01}\n\nIn this first workshop, we will get familiar with R.\n\n::: {.callout-tip title=\"Learning Objectives\"}\nAt the end of this session, learners should be able to:\n\n1.  Use RStudio, R projects and R scripts\n\n2.  Perform basic mathematical operations, comparisons and function calls in R\n\n3.  Employ variables to store the results of analyses\n\n4.  Describe the different data types and data structures used in R\n\n5.  Compose R code that uses subsetting to operate on vectors and data frames\n:::\n\n## Getting started {#sec-starting}\n\nWelcome to the first R coding workshop! You've had a go at writing some basic R code in tutorial 1 last week, and today we will build on that to develop a strong foundation in R.\n\n### Opening our project {#sec-project}\n\nThe first thing we need to do is open the R project that we will use in these workshops. As covered in lecture 2, projects are a way we can organise our work in RStudio, so that we can resume where we left off and keep different analyses separate. Any time you start working on something new (like these workshops!) it is recommended that you start a new project. To make things easier, we have pre-made an R project with all of the data you will need for the workshops. If you haven't already, download it using the button below:\n\n{{< downloadthis data/BIOL90042_workshops.zip dname=\"BIOL90042_workshops\" label=\"Download the R project for this course\" icon=\"file-earmark-arrow-down\" type=\"primary\" class=\"data-button\" id=\"rproj\" >}}\n\nOnce downloaded, you can move this file to wherever you'd like on your computer, and **unzip it** (on mac: double-click, on windows: right-click, then 'extract all').\n\nInside the 'BIOL90042_workshops' folder, you should see two things: a sub-folder called 'data' and an R project file:\n\n![The project folder contains a 'data' sub-folder and an R project file](images/S01F00_rproject.png){width=\"960\"}\n\nDouble-click on this `.Rproj` (R project) file, and it should open up in RStudio. You now have a new R session, where you are working inside of a project called 'r_course'.\n\nYou can see the current project you're working on, switch between projects or create a new project using the menu in the top right hand corner of RStudio:\n\n![In the top right hand corner of RStudio, you can see all of your projects](images/S01F01_make_project.png){width=\"960\"}\n\n::: {.callout-note title=\"Name with underscores, not spaces\"}\nYou'll notice I named my project using an underscore (r_course) rather than a space (r course). **In general, when coding we want to name things without spaces**, so that it is clear to the computer that we are talking about a single entity (the 'r_course') as opposed to multiple things ('r' and 'course'). We'll revisit this idea later in the session in @sec-variables\n:::\n\n### Creating an R script {#sec-createRScript}\n\nNow that our project is set up, recall that we need to create a file to write our code in:\n\n![How to create a new R Script](images/S01F05_new_script.png){width=\"960\"}\n\nRemember that this file is called an **R Script**. Don't forget to save your R Script as you work so you don't lose your progress! You can do this through the file menu or by using the keyboard shortcut {{< kbd Cmd-S >}}.\n\n### Writing our first piece of code\n\nNow we are ready to write some code! You might like to start with some of what we learned last week, in section @sec-maths of the ebook.\n\nBefore we get into writing code though, let's first learn about one of the most important concepts in programming: comments. Comments are lines of our script that begin with `#` and they are ignored by the computer: they are just notes that we write to ourselves. It's really important to write 'well-commented' code, with plenty of comments that clearly explain what your code is doing, so that your script can easily be understood by whoever looks at it next (whether this is someone else or you revisiting an analysis many months later!)\n\n::: {.callout-warning title=\"Don't forget your #\"}\nIf you forget the `#` at the start of your comment, R will try to interpret your notes as actual code, and you'll get an error message:\n\n\n::: {.cell}\n\n```{.r .cell-code}\noops I forgot the hashtag\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in parse(text = input): <text>:1:6: unexpected symbol\n1: oops I\n         ^\n```\n\n\n:::\n:::\n\n:::\n\nDuring this course, we will practice writing well-commented code, but here is an example of how we could write comments to explain the code for one plus one:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate one plus one\n1 + 1 # the + symbol means plus\n```\n:::\n\n\nNote that comments can be written on their own line or at the end of a line after the code. Crucially, you cannot write any code after a `#` on the same line, as R will ignore it. This is sometimes useful for 'commenting out' code that you don't want to run, but want to keep in your script for later use.\n\n::::::::::::::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding\n\n:::::::: question\n1\\. Which R expression would give me a result of 10?\n\n::::::: choices\n::: {.choice .correct-choice}\n`10 + 0 # + 60`\n:::\n\n::: choice\n`1 + 2`\n:::\n\n::: choice\n`# 5 + 5`\n:::\n\n::: choice\n`100 - 50`\n:::\n:::::::\n::::::::\n\n:::::::: question\n2\\. What would be the result of running this line of R code: `# test 1+1`\n\n::::::: choices\n::: choice\n1\n:::\n\n::: choice\n2\n:::\n\n::: choice\nAn error\n:::\n\n::: {.choice .correct-choice}\nNothing\n:::\n:::::::\n::::::::\n\n<details>\n\n<summary>Solutions</summary>\n\n<p>\n\n1.  `10 + 0 # + 60` is equal to 10, because the + 60 is after the comment symbol `#`. If you're not sure, try copy-pasting this code into the console and running it! The best way to learn is by doing.\n\n2.  The code `# test 1+1` is a comment, because it starts with a `#`. This means R ignores it: if you run this code, you won't see any output in the console.\n\n</p>\n\n</details>\n:::::::::::::::\n\n## Comparisons {#sec-comparisons}\n\nNow, let's learn some new R code! We'll start with comparisons.\n\nR can perform comparisons, using the following notation:\n\n| Comparison                    | Code         |\n|-------------------------------|--------------|\n| Equal to                      | `==`         |\n| Not equal to                  | `!=`         |\n| Greater/less than             | `>` or `<`   |\n| Greater/less than or equal to | `>=` or `<=` |\n\n::: {.callout-warning title=\"Mind your equal signs!\"}\nBe careful to use double equal signs `==` when checking for equality. If you use only one, you'll get an error:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 == 1 # this is TRUE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\n1 = 1 # this gives an error\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `1 = 1`:\n! invalid (do_set) left-hand side to assignment\n```\n\n\n:::\n:::\n\n:::\n\nComparisons in R return either `TRUE` or `FALSE`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n10 > 10\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n10 >= 10\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nYou can also negate the result of a comparison or any TRUE/FALSE value by using the `!` operator before the expression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# gives FALSE (i.e. not TRUE)\n!TRUE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n# gives TRUE: 1 is not equal to 2, but we've negated the result\n!(1 == 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nThis is really useful for filtering data, which we will cover in [Session @sec-workshop02]\n\n::::::::::::::::::::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding\n\n:::::::: question\n1\\. What would be the result of running this R code: `10 >= 10`\n\n::::::: choices\n::: choice\n10\n:::\n\n::: choice\n`FALSE`\n:::\n\n::: {.choice .correct-choice}\n`TRUE`\n:::\n\n::: choice\nAn error\n:::\n:::::::\n::::::::\n\n:::::::: question\n2\\. Which of the following R expressions would give me a result of `FALSE`?\n\n::::::: choices\n::: choice\n`1 == 1`\n:::\n\n::: choice\n`1 != (3 - 4) * 1`\n:::\n\n::: choice\n`1 = 10`\n:::\n\n::: {.choice .correct-choice}\n`1 == 2`\n:::\n:::::::\n::::::::\n\n:::::::: question\n3\\. What would be the result of running this R code: `!TRUE`\n\n::::::: choices\n::: {.choice .correct-choice}\n`FALSE`\n:::\n\n::: choice\n`TRUE`\n:::\n\n::: choice\nAn error\n:::\n\n::: choice\nNothing\n:::\n:::::::\n::::::::\n\n<details>\n\n<summary>Solutions</summary>\n\n<p>\n\n1.  `10 >= 10` is TRUE because 10 is equal to 10, and we are using the greater than or equal to operator, `>=`.\n2.  `1 == 2` is the only expression that would give a result of `FALSE`. Be mindful that `1 = 10` is not a valid expression in R, and would give an error (since we need to use the double equal sign `==` for comparisons).\n3.  `!TRUE` is `FALSE` because we are negating the value using `!`.\n\n</p>\n\n</details>\n:::::::::::::::::::::\n\n## Variables {#sec-variables}\n\n### What's a variable?\n\nA variable (also known as an object) in R is like a label we can use to keep track of values. We assign (save) values to variables so that we can refer to them later.\n\nFor example, let's say I use R to do some maths:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(2 + 6) * 7\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 56\n```\n\n\n:::\n:::\n\n\nR outputs simply the result. To use this value later, I would need to assign the output to a variable.\n\nVariables are assigned with the assignment operator `<-` (you can type this using the {{< kbd < >}} and {{< kbd - >}} keys, or use the shortcut {{< kbd mac=Option- win=alt- >}}).\n\n::: {.callout-note title=\"Assignment arrows\"}\nYou might be familiar with assigning values to variables using the equal sign `=`, which is used in other programming languages and in maths. Although this does also work in R, **it's preferred to use the arrow** `<-` as this makes it really clear that a variable is being assigned. In this course we'll be using `<-`.\n:::\n\nReturning to our example, let's save the result of the above calculation to a variable called `my_number`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# assign the result to my_number\nmy_number <- (2 + 6) * 7\n```\n:::\n\n\nHere, R has performed the calculation to the right of the arrow (`(2 + 6) * 7`) and assigned the result of this to the `my_number` variable.\n\nYou'll notice that this line of code doesn't produce any output, because it has gone straight into our variable. If we want to know the value of `my_number`, we can either run it as a line of R code, like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_number\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 56\n```\n\n\n:::\n:::\n\n\nOr, we can look at the environment panel in RStudio:\n\n![We can see our variables and their values in the environment panel](images/S01F07_environment_panel.png)\n\n### Using variables in R code\n\nVariables can be used in place of values (e.g. numbers) in R code. For example, we can use the `my_number` variable in a calculation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# multiply my_number by 2\nmy_number * 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 112\n```\n\n\n:::\n:::\n\n\nAs the name suggests, variables can vary! We can assign a new value to a variable at any time:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# change the value of my_number to 12\nmy_number <- 12\nmy_number\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12\n```\n\n\n:::\n:::\n\n\nBecause the right hand side of the arrow is evaluated first, you can also assign to a variable a calculation that involves itself:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add 5 to my_number\nmy_number <- my_number + 5\nmy_number # value is now 17 since 12 + 5 = 17\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 17\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning title=\"Careful of cases!\"}\nOne thing we need to be careful of when using variables is that R is case-sensitive. This means that `MY_NUMBER` is not the same as `my_number`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create the my_number variable\nmy_number <- (2 + 6) * 7\n\n# produces error because MY_NUMBER is not the same as my_number\nMY_NUMBER\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError:\n! object 'MY_NUMBER' not found\n```\n\n\n:::\n:::\n\n:::\n\nThere's not really any harm in keeping variables around, but if you would like to remove them you can use the `rm()` function like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# assign a variable\nmy_variable <- 10\n\n# remove it\nrm(my_variable) # put the variable name inside the brackets\n```\n:::\n\n\nWe'll cover functions in more detail in @sec-functions.\n\nIf you want to remove ALL the variables you've assigned and start fresh, you can use the broom button in the environment panel:\n\n![The broom button removes all your variables](images/S01F09_broom_button.png){width=\"686\"}\n\nTry using the broom to clean up your environment after completing the practice exercises at the end of this section.\n\n### Choosing good variable names\n\nWhen naming variables, we need to follow these rules:\n\n+----------------------------------------------------------------------+----------------------------------------+\n| Rule                                                                 | Examples                               |\n+======================================================================+========================================+\n| **Variable names can only contain letters, numbers and underscores** | ✅ Allowed: `my_number`, `ID_2`        |\n|                                                                      |                                        |\n|                                                                      | ❌ Not allowed: `my_number!`, `price$` |\n+----------------------------------------------------------------------+----------------------------------------+\n| **Variable names can't start with a number**                         | ✅ Allowed: `my_number_2`              |\n|                                                                      |                                        |\n|                                                                      | ❌ Not allowed: `2_my_number`          |\n+----------------------------------------------------------------------+----------------------------------------+\n| **Variable names can't contain spaces**                              | ✅ Allowed: `my_number`                |\n|                                                                      |                                        |\n|                                                                      | ❌ Not allowed: `my number`            |\n+----------------------------------------------------------------------+----------------------------------------+\n\nIf we try to create a variable that breaks these rules, R will give an error:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# gives an error because we use a non-allowed character\npercentage% <- 100\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in parse(text = input): <text>:2:11: unexpected input\n1: # gives an error because we use a non-allowed character\n2: percentage% <- 100\n             ^\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# gives an error because we start with a number\n1place <- 1\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in parse(text = input): <text>:2:2: unexpected symbol\n1: # gives an error because we start with a number\n2: 1place\n    ^\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# gives an error because we have a space\nmy age <- 5\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in parse(text = input): <text>:2:4: unexpected symbol\n1: # gives an error because we have a space\n2: my age\n      ^\n```\n\n\n:::\n:::\n\n\nRStudio will try to help you spot these mistakes in your script, by using underlining them in red:\n\n![RStudio underlines errors in your code](images/S01F08_variable_errors.png)\n\nBeyond those three key rules, there are also some best practices we should try to keep in mind when naming our variables:\n\n-   Try not to use capital letters. Since R is case sensitive, `Genes` is a different variable to `genes`. It can be easy to forget to use a capital letter, so it's generally better to avoid them if you can.\n\n-   Use descriptive names. It's better to use a longer name that describes what the variable is for, rather than a short name that doesn't give much information. For example, `gene_counts` is better than `gc`. You'll thank yourself later when you come back to your code and can't remember what `gc` stands for!\n\n-   Avoid using names that are already used in R. For example, `mean` is a function in R that calculates the average of a set of numbers. If you use `mean` as a variable name, this could lead to errors: how will R know if you are referring to the function `mean` or your variable `mean`?\n\n::::::::::::::::::::::::::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding\n\n:::::::: question\n1\\. How would I assign the value of 10 to a variable called `my_variable`?\n\n::::::: choices\n::: choice\n`10`\n:::\n\n::: {.choice .correct-choice}\n`my_variable <- 10`\n:::\n\n::: choice\n`my_variable = 10`\n:::\n\n::: choice\n`my variable <- 10`\n:::\n:::::::\n::::::::\n\n:::::::: question\n2\\. I have assigned the value of 10 to a variable called `my_variable` as in Q1. What then would be the output from running this line of R code: `my_variable + 5`?\n\n::::::: choices\n::: choice\nAn error\n:::\n\n::: choice\nNothing\n:::\n\n::: choice\n5\n:::\n\n::: {.choice .correct-choice}\n15\n:::\n:::::::\n::::::::\n\n:::::::: question\n3\\. I have assigned the value of 10 to a variable called `my_variable` as in Q1. If I run the code `my_variable <- my_variable + 10`, what is the new value of `my_variable`?\n\n::::::: choices\n::: choice\n10\n:::\n\n::: choice\n25\n:::\n\n::: {.choice .correct-choice}\n20\n:::\n\n::: choice\n`my_variable`\n:::\n:::::::\n::::::::\n\n:::::::: question\n4\\. Which of the following is a valid variable name?\n\n::::::: choices\n::: choice\n`10th_place`\n:::\n\n::: choice\n`(n)_mice`\n:::\n\n::: choice\n`disease status`\n:::\n\n::: {.choice .correct-choice}\n`expression_level`\n:::\n:::::::\n::::::::\n\n<details>\n\n<summary>Solutions</summary>\n\n<p>\n\n1.  `my_variable <- 10` is the correct way to assign the value of 10 to a variable called `my_variable`. Remember the arrow `<-` is used for assignment in R.\n2.  The output would be 15, since `my_variable` is 10 and we are adding 5 to it.\n3.  The new value of `my_variable` would be 20, since we are adding 10 to the current value of `my_variable` (which is 10). Note that even though we added 5 to `my_variable` earlier, this value is not saved anywhere (since we didn't assign it), so we are starting from the original value of 10.\n4.  `expression_level` is the only valid variable name. `10th_place` starts with a number, `(n)_mice` contains brackets, and `disease status` contains a space.\n\n</p>\n\n</details>\n:::::::::::::::::::::::::::\n\n## Functions {#sec-functions}\n\n### Functions and arguments\n\nFunctions are programs that take inputs (also known as arguments) and produce outputs. They have a name, followed by round brackets `()` which contain the arguments.\n\nFor example, when we used the code `rm(my_variable)` earlier, the function `rm()` was taking the input (argument) `my_variable` and producing the output of deleting that variable.\n\nSome functions have multiple arguments, which are specified by separating them with commas. Arguments have a set order in which they can be given, or they can be referred to specifically by their name (using a equal sign `=` to provide a value).\n\nAs an example, the `round()` function rounds a number to a specified number of decimal places. The first argument is the number to be rounded, and the second argument is the number of decimal places to round to.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# we'll use this decimal to demonstrate the round function\ndecimal <- 3.14159\n\n# round to 3 decimal places\nround(decimal, digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.142\n```\n\n\n:::\n\n```{.r .cell-code}\n# we don't have to specify the argument name if we provide the arguments in the correct order\nround(decimal, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.142\n```\n\n\n:::\n:::\n\n\nWe can see that both of our calls to the `round()` function produced the same result, but the first is easier to understand since we explicitly specified the argument.\n\nMany arguments have default values so you don't need to specify every argument for every function. For example, the `round()` function has a default value of 0 for the `digits` argument, so if you don't specify it, the number will be rounded to the nearest whole number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(decimal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n:::\n\n\n::: {.callout-warning title=\"Common errors with functions\"}\nHere are some common errors you might encounter when using functions. Have a look at the code below and read the error messages to see how the two relate. This will help you to fix typos/errors in your own code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# forgot to enclose the arguments in brackets\nround 3.14159\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in parse(text = input): <text>:2:7: unexpected numeric constant\n1: # forgot to enclose the arguments in brackets\n2: round 3.14159\n         ^\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# forgot the comma between the arguments\nround(3.14159 digits = 3)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in parse(text = input): <text>:2:15: unexpected symbol\n1: # forgot the comma between the arguments\n2: round(3.14159 digits\n                 ^\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# spelt the argument name wrong\nround(3.14159, digts = 3)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `round()`:\n! unused argument (digts = 3)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# forgot to close the brackets\nround(3.14159, digits = 3\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in parse(text = input): <text>:3:0: unexpected end of input\n1: # forgot to close the brackets\n2: round(3.14159, digits = 3\n  ^\n```\n\n\n:::\n:::\n\n\nRStudio will also flag some of these sorts of issues in the script panel, although it won't catch everything:\n\n![RStudio can help you to find errors in your function calls before you run the code](images/S01F15_errors_in_functions.png){width=\"900\"}\n:::\n\n### Getting help with functions: within R\n\nWhen you're using a function, you might not know what arguments it takes, what they do or what their default values are. Nobody can remember all of this information, so one of the most important skills in programming is learning how to access help.\n\nYou can access the help pages for a function by typing `?` followed by the name of the function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n?round\n```\n:::\n\n\nOr searching for the function in the help tab in RStudio:\n\n![You can search for functions directly in the help panel](images/S01F10_help_search.png){width=\"688\"}\n\nHere's what the help page looks like for the `round` function:\n\n![The help page for the round function](images/S01F11_help_page.png){width=\"688\"}\n\nHelp pages can sometimes be quite technical or complicated– for example the help page for `round` also describes various other similar functions for rounding numbers. Often the most important section to look at is the 'arguments' one:\n\n![Help pages have a section for describing arguments](images/S01F12_help_arguments.png){width=\"638\"}\n\nYou can also see help for functions in the script panel, as you are typing your code:\n\n![RStudio will show you a preview of the help page as you type a function name](images/S01F13_help_when_typing.png){width=\"1438\"}\n\nIt will also suggest you the names of arguments:\n\n![RStudio also suggests arguments for functions as you type](images/S01F14_help_when_typing_2.png){width=\"1682\"}\n\nSo, if you get stuck with how to use a function, wait a moment and see if RStudio will suggest what you need.\n\n### Getting help with functions: beyond R\n\nSometimes, the R help pages can be pretty tricky to understand, and they can't help you if you don't know the name of the function you need! In this course, we'll learn about lots of different functions, but even R experts need to look things up sometimes. Here are some good resources for getting help:\n\n-   **Google**. R is a pretty popular language, so if you google 'how to do x in R', you'll probably find an answer\n\n-   **Package vignettes**. Many R packages have vignettes, which are short guides to using the package. Once you find the name of a package you might want to use, you should go through their vignettes to see what functions are available and how to use them.\n\n-   **ChatGPT/Claude/Gemini** (or similar). AI tools can be really useful in helping you write code, although make sure you double-check the results because it can make mistakes. Revisit lecture 1 for tips on how to best use these.\n\n-   **Ask others**! There are lots of R users, and working together is often the best way to solve problems. This could be through online forums, like [StackOverflow](http://stackoverflow.com/questions/tagged/r) or in-person\n\nNo matter where you get your help, try to make sure you understand the code you find. Reading the help pages for new functions, or asking an AI to explain what code is doing is a great way to expand your R knowledge.\n\n::::::::::::::::::::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding\n\n:::::::: question\n1\\. What would be the result of running this R code: `round(3.14159, digits = 2)`\n\n::::::: choices\n::: choice\n3.14159\n:::\n\n::: choice\n3.141\n:::\n\n::: {.choice .correct-choice}\n3.14\n:::\n\n::: choice\n3\n:::\n:::::::\n::::::::\n\n2\\. Look up the help pages for the following functions, and describe what they do:\n\n-   `mean()`\n-   `Sys.Date()`\n-   `sin()`\n\n:::::::: question\n3\\. What is wrong with this line of R code: `round(3.14159, digits = 3`\n\n::::::: choices\n::: choice\nDigits is not a valid argument for the round function\n:::\n\n::: choice\nYou need to use a double equal sign `==` for the digits argument\n:::\n\n::: choice\nYou don't need to specify the digits argument\n:::\n\n::: {.choice .correct-choice}\nYou need to close the brackets at the end of the line\n:::\n:::::::\n::::::::\n\n:::::::: question\n4\\. Which of the following lines of R code will run without error?\n\n::::::: choices\n::: choice\n`rm(my_variable`\n:::\n\n::: choice\n`round(3.14159, Digits = 3)`\n:::\n\n::: choice\n`round(3.14159 digits = 3)`\n:::\n\n::: {.choice .correct-choice}\n`round(3.14159, 3)`\n:::\n:::::::\n::::::::\n\n<details>\n\n<summary>Solutions</summary>\n\n<p>\n\n1.  The result of running `round(3.14159, digits = 2)` would be 3.14. Remember the `round()` function rounds the number 3.14159 to 2 decimal places, according to the digits argument.\n2.  The `mean()` function calculates the average of a set of numbers, `Sys.Date()` returns the current date, and `sin()` calculates the sine of an angle (in radians).\n3.  The line of R code `round(3.14159, digits = 3` is missing a closing bracket at the end, which is why it would produce an error.\n4.  The line of R code `round(3.14159, 3)` will run without error. The other lines of code have errors: `rm(my_variable` is missing a closing bracket, `round(3.14159, Digits = 3)` has a typo in the argument name (argument names are case sensitive), and `round(3.14159 digits = 3)` is missing a comma between the arguments. Remember that we don't always need to specify the argument names if we provide the arguments in the correct order, which is why we could omit the `digits =` part in the correct line of code.\n\n</p>\n\n</details>\n:::::::::::::::::::::\n\n## Data types {#sec-dataTypes}\n\nEvery variable in R has a 'type'. The type tells R what kind of data it is and consequently what it can and can't do with the data. For example, it makes sense to perform mathematical functions like multiplication or division on numbers but not on words.\n\nThere are three basic types of data in R:\n\n+-------------+---------------------------------------------------------------------------------------------------+-------------------+\n| Type        | Description                                                                                       | Examples          |\n+=============+===================================================================================================+===================+\n| `logical`   | also known as 'boolean', true or false                                                            | `TRUE`            |\n|             |                                                                                                   |                   |\n|             |                                                                                                   | `FALSE`           |\n+-------------+---------------------------------------------------------------------------------------------------+-------------------+\n| `numeric`   | numbers                                                                                           | `1`               |\n|             |                                                                                                   |                   |\n|             |                                                                                                   | `0.523`           |\n|             |                                                                                                   |                   |\n|             |                                                                                                   | `10000`           |\n+-------------+---------------------------------------------------------------------------------------------------+-------------------+\n| `character` | text/numbers surrounded by quotation marks (double `\"\"` or single `''`). Also known as a 'string' | `'hello'`         |\n|             |                                                                                                   |                   |\n|             |                                                                                                   | `\"cat\"`           |\n|             |                                                                                                   |                   |\n|             |                                                                                                   | `\"my name is...\"` |\n+-------------+---------------------------------------------------------------------------------------------------+-------------------+\n\nThese are called 'atomic' data types as they are the most basic types of data from which other data types derive.\n\nYou can find the type of something using the `class()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"logical\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# whatever you put in quotation marks is always a character\nclass(\"hello\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(\"TRUE\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(\"123\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\nIt is important to know the type of your data because, as mentioned earlier, R will not let you perform certain operations on data of the wrong type. For example, you can't add two characters together:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# this works\n1 + 1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\n# but this gives an error\n\"1\" + \"1\"\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `\"1\" + \"1\"`:\n! non-numeric argument to binary operator\n```\n\n\n:::\n:::\n\n\nNor can you use the logical operator `!` on a character:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# this works\n!TRUE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n# but this gives an error\n!\"TRUE\"\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `!\"TRUE\"`:\n! invalid argument type\n```\n\n\n:::\n:::\n\n\nYou'll notice that the error messages for these two examples explain that R can't perform the operation you're asking it to do on that data type.\n\nIf you want to change the type of a piece of data, you can use the `as.x()` functions like (e.g. `as.logical()`, `as.numeric()`, and `as.character()`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# convert a number to a character\nas.character(100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"100\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# convert a character to a number\nas.numeric(\"100\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n:::\n\n\nOf course, it doesn't make sense to make some conversions. In the example below, we can't convert the word \"hello\" to a number, so we get an `NA`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# if a conversion is not possible, you'll get an NA\nas.numeric(\"hello\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: NAs introduced by coercion\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n:::\n\n\n::::::::::::::::::::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding\n\n:::::::: question\n1\\. What are the three atomic data types in R?\n\n::::::: choices\n::: {.choice .correct-choice}\nlogical, numeric, character\n:::\n\n::: choice\ninteger, float, string\n:::\n\n::: choice\ndataset, vector, matrix\n:::\n\n::: choice\nboolean, text, number\n:::\n:::::::\n::::::::\n\n:::::::: question\n2\\. How do you find the type of a piece of data in R?\n\n::::::: choices\n::: choice\nYou can't\n:::\n\n::: choice\nUsing the `type()` function\n:::\n\n::: choice\nGuess\n:::\n\n::: {.choice .correct-choice}\nUsing the `class()` function\n:::\n:::::::\n::::::::\n\n:::::::: question\n3\\. How would you convert the character \"TRUE\" to a logical?\n\n::::::: choices\n::: choice\n`TRUE`\n:::\n\n::: {.choice .correct-choice}\n`as.logical(\"TRUE\")`\n:::\n\n::: choice\nYou can't convert a character to a logical\n:::\n\n::: choice\nUsing the `logical()` function\n:::\n:::::::\n::::::::\n\n4\\. What are the types of the following?\n\n-   `11`\n\n-   `\"eleven\"`\n\n-   `TRUE`\n\n-   `!FALSE`\n\n-   `0.49826`\n\n-   `\"-0.53\"`\n\n-   `as.numeric(\"11\")`\n\n<details>\n\n<summary>Solutions</summary>\n\n<p>\n\n1.  The three atomic data types in R are logical, numeric, and character.\n2.  You can find the type of a piece of data in R using the `class()` function.\n3.  To convert the character \"TRUE\" to a logical, you would use `as.logical(\"TRUE\")` (we always use 'as...' functions to convert between types).\n4.  The types are:\n    -   `11` is numeric\n    -   `\"eleven\"` is character\n    -   `TRUE` is logical\n    -   `!FALSE` is logical\n    -   `0.49826` is numeric\n    -   `\"-0.53\"` is character (even though it looks like a number, it is surrounded by quotation marks so it is a character)\n    -   `as.numeric(\"11\")` is numeric (since we converted the character \"11\" to a number with the `as.numeric()` function)\n\n</p>\n\n</details>\n:::::::::::::::::::::\n\n## Data structures {#sec-datastructures}\n\nBeyond the atomic data types, R has more complex data structures that can store multiple values. These are the building blocks of data analysis in R. The most common data structures are vectors, matrices, and data frames.\n\nThis figure summarises their key differences:\n\n![Overview of the three main data structures in R. 📷 credit: https://bookdown.org/introrbook/intro2r/](images/data-structure.png)\n\n### Vectors {#sec-vectors}\n\nA vector is a collection of values **of the same atomic type**. Values in a vector are laid out linearly, one after another.\n\nYou can create vectors with the `c()` function, like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# a vector of numbers\nc(1, 2, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 2 3\n```\n\n\n:::\n\n```{.r .cell-code}\n# a vector of characters\nc(\"a\", \"vector\", \"of\", \"characters\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"a\"          \"vector\"     \"of\"         \"characters\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# a vector of logicals\nc(TRUE, FALSE, TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  TRUE FALSE  TRUE\n```\n\n\n:::\n:::\n\n\nFun fact: the 'c' in `c()` stands for 'combine'.\n\nThere are a few ways to see the contents of a vector. You can simply type the name of the vector into the console, which will print out the whole thing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# in these examples we will use the letters vector that is\n# pre-loaded in R. It contains the alphabet in lowercase\nletters\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"a\" \"b\" \"c\" \"d\" \"e\" \"f\" \"g\" \"h\" \"i\" \"j\" \"k\" \"l\" \"m\" \"n\" \"o\" \"p\" \"q\" \"r\" \"s\"\n[20] \"t\" \"u\" \"v\" \"w\" \"x\" \"y\" \"z\"\n```\n\n\n:::\n:::\n\n\nYou'll notice that, in addition to the `[1]` that we usually see printed next to the output, there is also a `[20]`. This number is telling us where we are up to in the vector (so `[1]` means that line of output starts with the first element, `\"a\"` and `[20]` means that line of output starts with the 20th element of the vector, `\"t\"`). We'll learn a bit more about what square brackets mean in R in @sec-vectorsubset.\n\nBut what if we don't always want to print the whole thing? For long vectors, it's handy to use the `head()` and `tail()` functions to inspect just a few values. By default, these print the first and last 6 elements of a vector (you can change that by setting the `n` argument).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use head() and tail() to take a quick look\nhead(letters)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"a\" \"b\" \"c\" \"d\" \"e\" \"f\"\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(letters)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"u\" \"v\" \"w\" \"x\" \"y\" \"z\"\n```\n\n\n:::\n:::\n\n\nYou can also use functions to look at other features of a vector, like its type (using the `class()` function just as for single values) or its length (using the `length()` function):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find the class of a vector\nclass(letters)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# find the length of a vector\nlength(letters)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 26\n```\n\n\n:::\n:::\n\n\nJust like you can with single values, vectors can be assigned to variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npet_names <- c(\"sprinkle\", \"lucky\", \"coco\")\n```\n:::\n\n\nThese variables will show up in the 'Environment' tab in RStudio:\n\n![The environment panel shows vectors too](images/S01F16_environment_panel_vectors.png){width=\"800\"}\n\nYou'll notice vector variables are displayed a little differently to those with single values. The type (`chr`, for character) is displayed first, followed by `[1:3]` which tells you that the `pet_names` vector has elements from 1 to 3 (in other words, it has a length of 3). This is particularly helpful when part of the vector is cut off, like in this picture!\n\n::: {.callout-note title=\"Colon (:) notation for vectors\"}\nIn programming, the colon `:` is typically used to create sequences of numbers. You can use it to create a sequence of numbers from a starting point to an ending point.\n\nFor example, `1:5` creates a vector of numbers from 1 to 5:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1:5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 2 3 4 5\n```\n\n\n:::\n:::\n\n:::\n\nR is a **vectorised** language, which means that many functions and operations (like `*`, `+` etc) work directly on vectors without you having to write extra code. For example, we can use the `mean()` function to calculate the average of a vector of numbers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a vector of numbers\nnumbers <- c(1, 2, 3, 4, 5)\n\n# calculate the mean\nmean(numbers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n:::\n\n\nBecause the other data structures we'll cover are built on vectors, this concept will be useful for them as well.\n\n#### Subsetting vectors {#sec-vectorsubset}\n\nNow that we're starting to work with vectors, you might have seen the square brackets `[]` appearing in the R console and environment panels. In R, square brackets are used for subsetting, which is where we extract just part of a data structure, like a vector.\n\nTo subset, we first write the vector (usually it is stored within a variable, so this will just be the variable's name), then directly next to that with no spaces, write some square brackets with a number inside that defines the position (aka index) of the element(s) you want to extract. For example, let's say I want to get the 5th letter of the alphabet. I could subset the `letters` vector like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get the fifth letter of the alphabet\n# be careful that there is no space between 'letters' and the square bracket\n# also remember to close your brackets!\nletters[5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"e\"\n```\n\n\n:::\n:::\n\n\nThis returns `\"e\"`, the fifth letter of the alphabet. Using the colon notation described above, we can also extract a range of positions from the vector, for example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get the 10th to 15th letters of the alphabet\nletters[10:15]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"j\" \"k\" \"l\" \"m\" \"n\" \"o\"\n```\n\n\n:::\n:::\n\n\nIt should be noted that, unlike some other programming languages R uses **1-based indexing**. So that means that the first letter of the alphabet, 'a' can be accessed using `letters[1]`. The indexing is also inclusive, so 10:15 includes the 15th position.\n\nYou can also use negative numbers to remove elements. For example, to get the entire alphabet except for the first letter, we could use the index -1 like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# remove the first letter \nletters[-1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"b\" \"c\" \"d\" \"e\" \"f\" \"g\" \"h\" \"i\" \"j\" \"k\" \"l\" \"m\" \"n\" \"o\" \"p\" \"q\" \"r\" \"s\" \"t\"\n[20] \"u\" \"v\" \"w\" \"x\" \"y\" \"z\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# equivalent to this\nletters[2:26]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"b\" \"c\" \"d\" \"e\" \"f\" \"g\" \"h\" \"i\" \"j\" \"k\" \"l\" \"m\" \"n\" \"o\" \"p\" \"q\" \"r\" \"s\" \"t\"\n[20] \"u\" \"v\" \"w\" \"x\" \"y\" \"z\"\n```\n\n\n:::\n:::\n\n\nThe way negative number indexing works in R is a little different to other languages also! If in doubt, just play around with the indexing, worst case scenario you have to try a few different expressions before you land on the correct one.\n\n::::::::::::::::::::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding\n\n:::::::: question\n1\\. Which of the following is NOT a valid vector in R?\n\n::::::: choices\n::: choice\n`c(TRUE, FALSE, FALSE)`\n:::\n\n::: {.choice .correct-choice}\n`(1, 2, 3, 4)`\n:::\n\n::: choice\n`1:10`\n:::\n\n::: choice\n`c(\"cat\", \"dog\", \"fish\")`\n:::\n:::::::\n::::::::\n\n:::::::: question\n2\\. What is the result of running this R code: `c(1, 2, 3) * 2`?\n\n::::::: choices\n::: choice\n`2(1, 2, 3)`\n:::\n\n::: choice\n`c(1, 2, 3, 1, 2, 3)`\n:::\n\n::: choice\n`c(1, 2, 3, 2)`\n:::\n\n::: {.choice .correct-choice}\n`c(2, 4, 6)`\n:::\n:::::::\n::::::::\n\n:::::::: question\n3\\. Which of the following will NOT give me the first 5 letters of the alphabet?\n\n::::::: choices\n::: {.choice .correct-choice}\n`head(letters)`\n:::\n\n::: choice\n`letters[1:5]`\n:::\n\n::: choice\n`letters[-6:-26]`\n:::\n\n::: choice\n`c(letters[1], letters[2], letters[3], letters[4], letters[5])`\n:::\n:::::::\n::::::::\n\n<details>\n\n<summary>Solutions</summary>\n\n1\\. The vector `(1, 2, 3, 4)` is not a valid vector: you need to use the `c()` function to create a vector in R. The exception is the colon `:` notation, which creates a sequence of numbers.\n\n2\\. The result of running `c(1, 2, 3) * 2` would be `c(2, 4, 6)`. This is because R is a vectorised language, so the `*` operator multiplies each element of the vector by 2.\n\n3\\. The code `head(letters)` will give the first **6** letters of the alphabet, because the default value of the n argument that controls the number of elements to print is 6 (check the help page by running `?head` in the console). You could get it to print the first 5 letters by writing `head(letters, n = 5)`. Of the other options, `letters[1:5]` uses the\n\n</details>\n:::::::::::::::::::::\n\n### Matrices {#sec-matrixbrief}\n\nA matrix is the two-dimensional extension of the vector-- it stores a collection of values **of the same type** that are laid out in a grid with rows and columns. In this subject, we will only really use matrices in the context of RNA-seq analysis, so we will cover them then, or you can consult the further reading @sec-matrices.\n\n### Data frames {#sec-dataframes}\n\nData frames are similar to matrices in that they store data in rows and columns. The difference is each column can have a different type: for example you could have a column of gene names (character), a column of gene counts (numeric) and another column telling you whether or not the gene is protein-coding (logical). For this reason, data frames are the most common data structure used in R.\n\nYou can create a data frame using the `data.frame()` function. The arguments are vectors of values to be put into the data frame, with the names of the vectors becoming the column names:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a data frame\nmouse_facts <- data.frame(\n  name = c(\"mickey\", \"minnie\", \"stuart\"),\n  age = c(12, 8, 16),\n  weight = c(39.7, 42.2, 46.3)\n)\n\n# print the data frame\nmouse_facts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    name age weight\n1 mickey  12   39.7\n2 minnie   8   42.2\n3 stuart  16   46.3\n```\n\n\n:::\n:::\n\n\nWhen creating a data frame, it's important that all vectors are the same length. If they're not, you'll get an error:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmouse_facts <- data.frame(\n  name = c(\"mickey\", \"minnie\", \"stuart\"),\n  age = c(12, 8), # forgot to add stuart's age!\n  weight = c(39.7, 42.2, 46.3)\n)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `data.frame()`:\n! arguments imply differing number of rows: 3, 2\n```\n\n\n:::\n:::\n\n\nFor the rest of this section, we'll use the `iris` data set that comes pre-loaded in R. This is a bigger data set that contains measurements of different species of iris flowers, and will help us to learn how to work with data frames in R.\n\nFirst, let's load in the dataset using the `data()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(iris)\n```\n:::\n\n\n`iris` has the class `data.frame`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"data.frame\"\n```\n\n\n:::\n:::\n\n\nJust like for vectors, there are functions to look at the contents of a data frame. This is useful as printing the whole data frame can be overwhelming if it's large (try printing `iris` and see for yourself!). The `head()` and `tail()` functions work the same way as for vectors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Sepal.Width Petal.Length Petal.Width Species\n1          5.1         3.5          1.4         0.2  setosa\n2          4.9         3.0          1.4         0.2  setosa\n3          4.7         3.2          1.3         0.2  setosa\n4          4.6         3.1          1.5         0.2  setosa\n5          5.0         3.6          1.4         0.2  setosa\n6          5.4         3.9          1.7         0.4  setosa\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Sepal.Length Sepal.Width Petal.Length Petal.Width   Species\n145          6.7         3.3          5.7         2.5 virginica\n146          6.7         3.0          5.2         2.3 virginica\n147          6.3         2.5          5.0         1.9 virginica\n148          6.5         3.0          5.2         2.0 virginica\n149          6.2         3.4          5.4         2.3 virginica\n150          5.9         3.0          5.1         1.8 virginica\n```\n\n\n:::\n:::\n\n\nYou can also use the `View()` function to open the data frame in a new tab in RStudio:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# don't forget the capital V!\nView(iris)\n```\n:::\n\n\nThis will open a new tab in RStudio with the data frame displayed in a spreadsheet-like format, where you can sort and filter the columns to get a better view of the data:\n\n![The View() function opens the data frame in a new tab in RStudio](images/S01F18_view_function.png){width=\"800\"}\n\nAnother way to view the data frame is by clicking on its name in the environment panel:\n\n![Clicking on the data frame's name in the environment panel opens it in the viewer](images/S01F19_env_panel_data_frame.png){width=\"800\"}\n\nThis panel also shows you the names and types of the columns in the data frame. You might notice that the `Species` is described as a factor, which is a special type of data in R that we'll cover in @sec-workshop03.\n\nBefore the column names, you'll see the `$` symbol. The dollar sign `$` is a shortcut used in R to access columns of a data frame. For example, to access the `Petal.Width` column of the `iris` data frame, you can use `iris$Petal.Width`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris$Petal.Width\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1] 0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 0.2 0.2 0.1 0.1 0.2 0.4 0.4 0.3\n [19] 0.3 0.3 0.2 0.4 0.2 0.5 0.2 0.2 0.4 0.2 0.2 0.2 0.2 0.4 0.1 0.2 0.2 0.2\n [37] 0.2 0.1 0.2 0.2 0.3 0.3 0.2 0.6 0.4 0.3 0.2 0.2 0.2 0.2 1.4 1.5 1.5 1.3\n [55] 1.5 1.3 1.6 1.0 1.3 1.4 1.0 1.5 1.0 1.4 1.3 1.4 1.5 1.0 1.5 1.1 1.8 1.3\n [73] 1.5 1.2 1.3 1.4 1.4 1.7 1.5 1.0 1.1 1.0 1.2 1.6 1.5 1.6 1.5 1.3 1.3 1.3\n [91] 1.2 1.4 1.2 1.0 1.3 1.2 1.3 1.3 1.1 1.3 2.5 1.9 2.1 1.8 2.2 2.1 1.7 1.8\n[109] 1.8 2.5 2.0 1.9 2.1 2.0 2.4 2.3 1.8 2.2 2.3 1.5 2.3 2.0 2.0 1.8 2.1 1.8\n[127] 1.8 1.8 2.1 1.6 1.9 2.0 2.2 1.5 1.4 2.3 2.4 1.8 1.8 2.1 2.4 2.3 1.9 2.3\n[145] 2.5 2.3 1.9 2.0 2.3 1.8\n```\n\n\n:::\n:::\n\n\nTry typing this code into your R script. You'll notice once you write `iris$`, RStudio will list out all of the columns like so:\n\n![RStudio will suggest column names as you type](images/S01F20_column_suggestions.png){width=\"800\"}\n\nYou can navigate through these suggestions using the up and down arrow keys, and press {{< kbd Enter >}} or {{< kbd Tab >}} to select the column you want.\n\nThese columns are vectors, so you can use the functions we've learned about so far to work with them:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find the class of the Petal.Width column\nclass(iris$Petal.Width)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# find the average Petal.Width column\nmean(iris$Petal.Width)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.199333\n```\n\n\n:::\n:::\n\n\nFinally, data frames are **mutable**, meaning that you can add additional columns to them. You can do this by specifying your new column name with the `dataset$column_name` notation, and then assigning a vector into it, like `dataset$new_column_name <- new_column_contents`.\n\nFor example, let's say I want to add a column to the `iris` dataset that contains the sepal length in cm (currently, they are in inches). Knowing that 1 inch is equal to 2.54 cm, I could create this column like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris$sepal_length_cm <- iris$Sepal.Length * 2.54\n```\n:::\n\n\nBe careful that, as we discussed above every column in a dataframe must have the same length. For example, if I tried to run the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris$test <- 1:100\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `$<-.data.frame`:\n! replacement has 100 rows, data has 150\n```\n\n\n:::\n:::\n\n\nI get an error, because iris has 150 rows (so each column is a vector of length 150), and I'm trying to add to it a column with length 100.\n\n::::::::::::::::::::::::::::::::: {.callout-important title=\"Practice exercises\"}\nTry these practice questions to test your understanding\n\n:::::::: question\n1\\. What is the difference between a matrix and a data frame?\n\n::::::: choices\n::: {.choice .correct-choice}\nA matrix has all elements of the same type, while a data frame can have different types in each column\n:::\n\n::: choice\nThey're the same thing\n:::\n\n::: choice\nA matrix can only contain numbers, while a data frame can contain numbers and text\n:::\n\n::: choice\nA matrix is used for mathematical operations, while a data frame is used for data analysis\n:::\n:::::::\n::::::::\n\n:::::::: question\n2\\. I wrote this code to create a data frame, but it gave me an error. What is wrong with it?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfavourite_fruits <- data.frame(\n  fruit = c(\"apple\", \"banana\", \"cherry\"),\n  colour = c(\"red\", \"yellow\", \"red\"),\n  price = c(0.5, 0.3)\n)\n```\n:::\n\n\n::::::: choices\n::: choice\nThe column names are not in quotation marks\n:::\n\n::: {.choice .correct-choice}\nThe columns are not the same length: 'fruit' and 'colour' have 3 elements, but 'price' has 2\n:::\n\n::: choice\nIt's not allowed to have character columns and numeric columns in the same data frame\n:::\n\n::: choice\nYou should use the `data()` function instead of `data.frame()`\n:::\n:::::::\n::::::::\n\n:::::::: question\n3\\. What is NOT a way that I could view the contents of a data frame in R?\n\n::::::: choices\n::: choice\nRunning the name of the data frame as code in the R script panel\n:::\n\n::: choice\nTyping the name of the data frame into the console\n:::\n\n::: choice\nClicking on its name in the environment panel\n:::\n\n::: {.choice .correct-choice}\nUsing the `view()` function\n:::\n:::::::\n::::::::\n\n:::::::: question\n4\\. I have created the `mouse_facts` data frame using the code below. How would I calculate the average age of the mice?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmouse_facts <- data.frame(\n  name = c(\"mickey\", \"minnie\", \"stuart\"),\n  age = c(12, 8, 16),\n  weight = c(39.7, 42.2, 46.3)\n)\n```\n:::\n\n\n::::::: choices\n::: choice\nmean(age)\n:::\n\n::: {.choice .correct-choice}\nmean(mouse_facts\\$age)\n:::\n\n::: choice\naverage(age)\n:::\n\n::: choice\naverage(mouse_facts\\$age)\n:::\n:::::::\n::::::::\n\n:::::::: question\n5\\. How can I add a new column to the `mouse_facts` data frame above that contains the favourite food of each mouse? (Hint: it's cheese, because they are mice 🧀🐁)\n\n::::::: choices\n::: choice\n`mouse_facts + c(\"cheese\", \"cheese\", \"cheese\")`\n:::\n\n::: choice\n`mouse_facts$fave_food = cheese`\n:::\n\n::: choice\n`fave_food <- c(\"cheese\", \"cheese\", \"cheese\")`\n:::\n\n::: {.choice .correct-choice}\n`mouse_facts$fave_food <- c(\"cheese\", \"cheese\", \"cheese\")`\n:::\n:::::::\n::::::::\n\n<details>\n\n<summary>Solutions</summary>\n\n1\\. The difference between a matrix and a data frame is that a matrix has all elements of the same type (could be character, logical or numeric), while a data frame can have different types in each column.\n\n2\\. The code to create the data frame `favourite_fruits` gave an error because the columns are not the same length: 'fruit' and 'colour' have 3 elements, but 'price' has 2. You can't create a data frame with columns of different lengths. As for the other options, you can have character and numeric columns in the same data frame, the column names don't need to be in quotation marks (although the code will work if they are), and the `data()` function is used to load R's pre-installed datasets, while `data.frame()` is used to create new data frames.\n\n3\\. Using the `view()` function is not a way to view the contents of a data frame in R. The correct function is `View()` (with a capital 'V'). All the other options are valid ways to view the contents of a data frame.\n\n4\\. To calculate the average age of the mice, you would use `mean(mouse_facts$age)`. This is because the `age` column is part of the `mouse_facts` data frame, so you need to use the `$` symbol to access it, and the function for calculating the average in R is `mean()`.\n\n5\\. The correct answer is `mouse_facts$fave_food <- c(\"cheese\", \"cheese\", \"cheese\")`, because this is accessing the `fave_food` column in the `mouse_facts` data frame, and giving it a vector of correct length (3). `mouse_facts$fave_food = cheese` is incorrect because cheese is a character, so needs to be in quotation marks,  `fave_food <- c(\"cheese\", \"cheese\", \"cheese\")` creates a vector named `fave_food` but doesn't put this vector into the `mouse_facts` data frame and `mouse_facts + c(\"cheese\", \"cheese\", \"cheese\")` is incorrect because we can't perform addition on a data frame in R.\n\n</details>\n:::::::::::::::::::::::::::::::::\n\n## Summary\n\nHere's what we've learnt in this session:\n\n-   How to use an R project (to keep our files organised) and how to write and run code from an R script (so that the code is saved as a record of our work)\n\n-   The operators for basic maths (`*`, `/`, `+` and `-`) and comparisons (`==`, `<`, `<=` and `!`)\n\n-   How to use functions and specify their arguments, as well as how to get help\n\n-   How to assign variables using the `<-` operator, and how to name them appropriately\n\n-   The three basic atomic data types in R (character, numeric and logical)\n\n-   Three different data structures in R (vectors, matrices and data frames)\n\n-   How to use the square brackets `[]`, colons `:`  to subset vectors\n\n-   How to use the `$` to access and create columns in a data frame\n\nTry the practice questions below to test your understanding!\n\n### Practice questions\n\n1.  What would be the result of evaluating the following expressions? You don't need to know these off the top of your head, use R to help! (Hint: some expressions might give an error. Try to think about why)\n\n    a.  `5 + 10`\n    b.  `100 >= (5 + 2) ^ 2`\n    c.  `!(100 > 1)`\n    d.  `500 = 5 * 100`\n    e.  `2fast <- \"zoom\"`\n    f.  `round(428.195721, 2)`\n    g.  `?t.test`\n    h.  `class(\"banana\")`\n    i.  `class(as.numeric(\"500\"))`\n    j.  `\"1\" + \"10\"`\n    k.  `length(1:100)`\n    l.  `sum(c(1, 2, 3, 4))`\n    m.  `head(iris)`\n    n.  `mean(iris$Sepal.Width)`\n    o.  `iris$Sepal.Width[1:5]`\n\n2.  Write some R code to complete the right-hand side of this comparison: `as.numeric(\"100\") * 3 ==`\n\n3.  I wrote the following R code, and got an error. How can I fix it?\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    # the number of frogs I counted\n    Frog_counts <- c(11, 2, 4, 9, 10)\n    \n    # convert to a proportion: divide by the sum\n    frog_counts / sum(Frog_counts)\n    ```\n    \n    ::: {.cell-output .cell-output-error}\n    \n    ```\n    Error:\n    ! object 'frog_counts' not found\n    ```\n    \n    \n    :::\n    :::\n\n\n4.  Load the `iris` data frame into your R session using `data(iris)`. What is the median petal length? Show the code you used to calculate this.\n\n5.  I'm working with the `iris` data frame, but I feel like it needs to be more dramatic. I would like to create a new data frame called `IRIS` where the species in the `Species` column are all in capital letters. How can I do this? (hint: the function `toupper()` might help you out here)\n\n<details>\n\n<summary>Solutions</summary>\n\n1.  The results of evaluating the expressions are:\n\n    a.  `5 + 10` is `15`\n    b.  `100 >= (5 + 2) ^ 2` is `TRUE`\n    c.  `!(100 > 1)` is `FALSE` (although 100 is greater than 1, the `!` operator negates this)\n    d.  `500 = 5 * 100` gives an error because we need two equals signs `==` to check for equality in R. Actually this code is trying to assign the value of `5 * 100` to the variable `500`, which is not allowed, because variable names can't start with a number.\n    e.  `2fast <- \"zoom\"` gives an error because variable names can't start with a number\n    f.  `round(428.195721, 2)` is `428.2`\n    g.  `?t.test` opens the help page for the `t.test()` function\n    h.  `class(\"banana\")` is `\"character\"`\n    i.  `class(as.numeric(\"500\"))` is `\"numeric\"`\n    j.  `\"1\" + \"10\"` gives an error because you can't add two character strings together\n    k.  `length(1:100)` is `100`\n    l.  `sum(c(1, 2, 3, 4))` is `10`\n    m.  `head(iris)` shows the first 6 rows of the `iris` data frame\n    n.  `mean(iris$Sepal.Width)` is the average of the `Sepal.Width` column in the `iris` data frame\n    o.  `iris$Sepal.Width[1:5]` will give the first 5 values of the `Sepal.Width` column from the `iris` dataset.\n\n2.  The right-hand side of the comparison `as.numeric(\"100\") * 3 ==` can be anything that results in 300 e.g. `300` or `299 + 1`, for example\n\n3.  The error in the code is because the variable name `Frog_counts` is not the same as `frog_counts`. R is case-sensitive, so it thinks you are trying to divide a variable that doesn't exist. To fix this, make sure all your variables have the same case (lowercase is better!):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n    # the number of frogs I counted\n    frog_counts <- c(11, 2, 4, 9, 10)\n\n    # convert to a proportion: divide by the sum\n    frog_counts / sum(frog_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.30555556 0.05555556 0.11111111 0.25000000 0.27777778\n```\n\n\n:::\n:::\n\n\n4.  To calculate the median petal length in the `iris` data frame, you can use `median(iris$Petal.Length)`\n\n5.  First, we would want to assign (i.e. copy) the contents of the `iris` data frame into our new `IRIS` data frame. Then, we can use the `toupper()` function on the `Species` column like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make a new variabled called IRIS that contains the \n# same data as the original iris data frame\nIRIS <- iris\n\n# replace the existing Species column with the Species column in upper case\nIRIS$Species <- toupper(IRIS$Species)\n\n# verify that the species is now in upper case\nhead(IRIS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Sepal.Width Petal.Length Petal.Width Species sepal_length_cm\n1          5.1         3.5          1.4         0.2  SETOSA          12.954\n2          4.9         3.0          1.4         0.2  SETOSA          12.446\n3          4.7         3.2          1.3         0.2  SETOSA          11.938\n4          4.6         3.1          1.5         0.2  SETOSA          11.684\n5          5.0         3.6          1.4         0.2  SETOSA          12.700\n6          5.4         3.9          1.7         0.4  SETOSA          13.716\n```\n\n\n:::\n:::\n\n\n</details>\n",
    "supporting": [
      "workshop_1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}